# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894d86a149f8697bc7db93b17e609eb9a4bab36caf926fa496957604fdea6a0b8923b7542c80c902198914eb3f1c97c28f1f24ebd3a439a451c128b924f1cb2d

test:
  secret_key_base: 5b66e5a6f4ebc13051ac54c1eedd16eaf5be6bd43ed119582bc690585560ee06f2b0021f7f3e2d1277d6048b07b026ad5319adbd8114b930b8900fdb5b603457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
